### PR TITLE
🔧 Fix support for Python 3.12

### LINKED ISSUE #40: ERROR with Python 3.12.1 and intuit-oauth==1.2.4
ERROR with python 3.12.1 and intuit-oauth==1.2.4:
```
     from intuitlib.client import AuthClient
   File "/usr/local/lib/python3.12/site-packages/intuitlib/client.py", line 19, in <module>
     from future.moves.urllib.parse import urlencode
   File "/usr/local/lib/python3.12/site-packages/future/moves/__init__.py", line 5, in <module>
     from future.standard_library import import_top_level_modules
   File "/usr/local/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
     import imp
 ModuleNotFoundError: No module named 'imp'
```

### PR DESCRIPTION
**Pull request by bdsoha**
The *very old* `from future.moves.urllib.parse import urlencode` statement is causing deprecation issues in `Python 3.12`.

```txt
Traceback (most recent call last):
  File "//authClient.py", line 1, in <module>
    from intuitlib.client import AuthClient
  File "/usr/local/lib/python3.12/site-packages/intuitlib/client.py", line 19, in <module>
    from future.moves.urllib.parse import urlencode
  File "/usr/local/lib/python3.12/site-packages/future/moves/__init__.py", line 5, in <module>
    from future.standard_library import import_top_level_modules
  File "/usr/local/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

Closes #40

### CODE REVIEW

**Comment by ej2** [comment]
This needs to be merged and a new release cut. I am trying to make some noise on the official forums: 
https://help.developer.intuit.com/s/question/0D5TR0000035IFl0AM/error-with-python-3121

It might help if anyone is having the same issue comments there.

**Comment by bdsoha** [comment]
FW: @getwater
https://github.com/intuit/oauth-pythonclient/pull/41#issuecomment-1875869289

**Comment by bdsoha** [comment]
Help needed from other contributors:

- @AndreaSuckro
- @athityakumar 
- @bw-intuit
- @chetanddesai
- @ghostwriternr

**Comment by robert-mings** [comment]
Hey @bdsoha, Robert with the Intuit Developer Team here.

Thank you for your contribution, logic looks good. Can I confirm if you've validated the following methods:
- `get_authorization_url`
- `get_bearer_token`
- `refresh`

**Comment by bdsoha** [comment]
@robert-mings If you are referring to executing the unit-tests, then yes.

**Comment by bdsoha** [comment]
@robert-mings I added a *workflow* to run unit tests.

**Comment by robert-mings** [comment]
Thanks @bdsoha - could you split the workflow into a separate PR? We'll get it merged once that's complete.

**Comment by bdsoha** [comment]
@robert-mings Done!

**Comment by robert-mings** [comment]
Thanks again @bdsoha, merged.

**Comment by carderne** [comment]
Any plan to release this change to PyPI?

**Comment by robert-mings** [comment]
@carderne Yes! We're looking to bundle one additional change before releasing to PyPI. This should be updated by the end of this week.

**Comment by robert-mings** [comment]
@carderne V1.2.5 is now on PyPI and includes removal of the future dependency altogether! Let us know how it goes.

**Pull request merged**
